name: Update dependencies

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Using Node 18
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Update npm version to latest
              run: npm install -g npm@latest # stop showing warnings about the lockfile
            - name: Install dependencies
              run: |
                  npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
                  npm install --production=false
              env:
                  NODE_AUTH_TOKEN: ${{github.token}}
                  NODE_ENV: production # combined with --production ensures no patches are attempted in CI
            - name: Temporary - update generate-readme to v3
              run: npx npm-check-updates @userscripters/generate-readme -u
            - name: Update to the latest minor/patch version
              run: |
                  npx npm-check-updates -u --target minor
                  npm run readme --if-present
                  git add README.md
            - name: Install updated dependencies & update lockfile
              run: |
                  npm install
                  npm update
            - name: Make sure everything's ok
              run: npm test
            - name: Push changes to GitHub
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git diff --quiet && git diff --staged --quiet || (git add package*.json && git commit -m "$(date +%F) Automated dependencies update")
                  git push
